### ISSUE TITLE
Release notes in GH releases

### ISSUE THREAD

**Issue by morganchristiansson** [pree/helm-charts#198]
Would be nice with auto generated release notes

It's pretty easy to enable. I created+tested a PR for another project here: https://github.com/influxdata/helm-charts/pull/581

I can create a PR here if wanted?

**Comment by morganchristiansson** [comment]
Example release with release notes: https://github.com/morganchristiansson/influxdata-charts/releases/tag/telegraf-1.8.34

**Comment by morganchristiansson** [comment]
@pree release notes plz?

**Comment by pree** [comment]
Hi @morganchristiansson, sorry for the late comment. I was on holiday and didnt have any Internet. Yes, sure I'm happy with contributions and think release notes would be a great addition :)

**Comment by morganchristiansson** [comment]
Awesome! I submitted a PR.

I have notifications for new releases enabled on this repo and it's difficult to check what actually changed in a release without release notes.

Thanks for maintaining the home-assistant and sonarr charts.
